# -*- mode: ruby -*-
# vi: set ft=ruby :

# Based on https://github.com/nekonenene/vagrant-ubuntu-gui/blob/master/Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  # config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "provision.sh"
end
